# Generated by Django 5.0.4 on 2025-05-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(max_length=300)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_status', models.CharField(max_length=100)),
            ],
        ),
    ]
