# Generated by Django 5.0.4 on 2025-05-20 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='date',
            field=models.TextField(default=datetime.datetime.now, max_length=200),
        ),
    ]
